# docker-compose up
# sudo podman compose up
# Look to Mongo-Express at http://localhost:8081

services:
#  app:
#    container_name: python_app
#   image: python_app
#   ports:
#      - "8000:8000"
#    networks:
#     - python_app
#    build:
#      context: ../
#      dockerfile: ./infra/Dockerfile
#    env_file:
#      - .env
#    depends_on: 
#      - mongo
#      - mongo-express

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db  # Volume from data of MongoDB
    environment:
      - MONGO_DB=${MONGO_DB}
    #  - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
    #  - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=${ME_CONFIG_MONGODB_SERVER}
    #  - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
    #  - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    depends_on: 
      - mongo

networks:
  db:
  mongo-express:
#  app:

volumes:
  mongo_data:  # Volume
